swagger: "2.0"
info:
  title: aliasme.proto
  version: version not set
tags:
  - name: UserService
  - name: EmailService
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/api/v1/users:
    post:
      summary: Create a new user
      operationId: UserService_CreateUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeUser'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/aliasmeCreateUserRequest'
      tags:
        - UserService
  /api/v1/aliases:
    get:
      summary: List aliases for a user
      operationId: EmailService_ListAliases
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeListAliasesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: userId
          in: query
          required: false
          type: string
      tags:
        - EmailService
    post:
      summary: Create email alias
      operationId: EmailService_CreateAlias
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeAlias'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/aliasmeCreateAliasRequest'
      tags:
        - EmailService
  /api/v1/aliases/{id}:
    delete:
      operationId: EmailService_DeleteAlias
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeDeleteAliasResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - EmailService
    put:
      operationId: EmailService_UpdateAlias
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeAlias'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              emailId:
                type: string
              aliasPrefix:
                type: string
      tags:
        - EmailService
  /api/v1/emails:
    post:
      summary: Register a new email address
      operationId: EmailService_RegisterEmail
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeEmail'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/aliasmeRegisterEmailRequest'
      tags:
        - EmailService
  /api/v1/emails/verify:
    post:
      summary: Verify email address
      operationId: EmailService_VerifyEmail
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeEmail'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/aliasmeVerifyEmailRequest'
      tags:
        - EmailService
  /api/v1/users/{id}:
    get:
      summary: Get user by ID
      operationId: UserService_GetUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeUser'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - UserService
    delete:
      summary: Delete user
      operationId: UserService_DeleteUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeDeleteUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - UserService
    put:
      summary: Update user
      operationId: UserService_UpdateUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeUser'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
      tags:
        - UserService
  /api/v1/users/email/{email}:
    get:
      operationId: UserService_GetUserByEmail
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/aliasmeGetUserByEmailResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: email
          in: path
          required: true
          type: string
      tags:
        - UserService
definitions:
  aliasmeAlias:
    type: object
    properties:
      id:
        type: string
      userId:
        type: string
      emailId:
        type: string
      aliasAddress:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
    title: Alias related messages
  aliasmeCreateAliasRequest:
    type: object
    properties:
      userId:
        type: string
      emailId:
        type: string
      aliasPrefix:
        type: string
  aliasmeCreateUserRequest:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      password:
        type: string
  aliasmeDeleteAliasResponse:
    type: object
    properties:
      success:
        type: boolean
  aliasmeDeleteUserResponse:
    type: object
    properties:
      success:
        type: boolean
  aliasmeEmail:
    type: object
    properties:
      id:
        type: string
      userId:
        type: string
      address:
        type: string
      verified:
        type: boolean
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
    title: Email related messages
  aliasmeGetUserByEmailResponse:
    type: object
    properties:
      userId:
        type: string
  aliasmeListAliasesResponse:
    type: object
    properties:
      aliases:
        type: array
        items:
          type: object
          $ref: '#/definitions/aliasmeAlias'
  aliasmeRegisterEmailRequest:
    type: object
    properties:
      userId:
        type: string
      emailAddress:
        type: string
  aliasmeUser:
    type: object
    properties:
      id:
        type: string
      username:
        type: string
      email:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
    title: User related messages
  aliasmeVerifyEmailRequest:
    type: object
    properties:
      token:
        type: string
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
